//! Codegen the static translations manifest from
//! `assets/manifest.json` (produced by the offline data pipeline)
//! into `$OUT_DIR/translations_manifest.rs`, which `src/manifest.rs`
//! includes. This lets the binary know — at compile time — what all
//! 11 translations look like (codes, names, languages, licenses,
//! attribution, sizes, sha256s) so it can fetch the ones that
//! aren't bundled.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_in = PathBuf::from("assets/manifest.json");
    println!("cargo:rerun-if-changed={}", manifest_in.display());

    let raw = fs::read_to_string(&manifest_in)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest_in.display()));
    let m: Manifest = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("parse {}: {e}", manifest_in.display()));

    let mut entries = m.translations;
    entries.sort_by(|a, b| a.code.cmp(&b.code));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from assets/manifest.json. Do not edit.\n\n");

    out.push_str(&format!(
        "#[allow(dead_code, reason = \"scrollmapper provenance; useful for a future --version --verbose\")]\n\
         pub const SCROLLMAPPER_COMMIT: &str = {:?};\n\n",
        m.scrollmapper_commit
    ));

    out.push_str("pub const TRANSLATIONS: &[TranslationManifestEntry] = &[\n");
    for t in &entries {
        out.push_str(&format!(
            "    TranslationManifestEntry {{\n\
             \x20       code: {:?},\n\
             \x20       name: {:?},\n\
             \x20       language: {:?},\n\
             \x20       license: {:?},\n\
             \x20       attribution: {:?},\n\
             \x20       file: {:?},\n\
             \x20       sha256: {:?},\n\
             \x20       compressed_size: {},\n\
             \x20       decompressed_size: {},\n\
             \x20   }},\n",
            t.code,
            t.name,
            t.language,
            t.license,
            t.attribution,
            t.file,
            t.sha256,
            t.compressed_size,
            t.decompressed_size,
        ));
    }
    out.push_str("];\n\n");

    if let Some(x) = &m.xrefs {
        out.push_str(&format!(
            "#[allow(dead_code, reason = \"used by fetch::xrefs once the K-popup wires \
             prompt-to-download — see Db::attach_xrefs\")]\n\
             pub const XREFS: XrefsManifestEntry = XrefsManifestEntry {{\n\
             \x20   file: {:?},\n\
             \x20   sha256: {:?},\n\
             \x20   compressed_size: {},\n\
             \x20   decompressed_size: {},\n\
             }};\n",
            x.file, x.sha256, x.compressed_size, x.decompressed_size
        ));
    } else {
        panic!("manifest.json has no xrefs entry — the pipeline must produce one");
    }

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(out_dir).join("translations_manifest.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

#[derive(serde::Deserialize)]
struct Manifest {
    scrollmapper_commit: String,
    translations: Vec<TranslationEntry>,
    xrefs: Option<XrefsEntry>,
}

#[derive(serde::Deserialize)]
struct TranslationEntry {
    code: String,
    name: String,
    language: String,
    license: String,
    attribution: String,
    file: String,
    sha256: String,
    compressed_size: u64,
    decompressed_size: u64,
}

#[derive(serde::Deserialize)]
struct XrefsEntry {
    file: String,
    sha256: String,
    compressed_size: u64,
    decompressed_size: u64,
}
